site_name: Physiopy
site_description: Physiopy
site_author: The Physiopy developers
site_url: https://physiopy.github.io
#google_analytics: ['UA-170131052-1', 'www.nipreps.org']

# Copyright
copyright: Copyright &copy; 2020

nav:
    - Home: docs/index.md
    - Libraries:
      - phys2bids: docs/libraries/phys2bids.md
      - phys2denoise: docs/libraries/phys2denoise.md
      - peakdet: docs/libraries/peakdet.md
    - Community:
      - Welcome: docs/community/index.md
      - Membership: docs/community/members.md
      - Collecting physiological data: docs/community/best-practices.md
      - Contributing: docs/community/contributing.md
      - Contributor Guide: docs/community/contributorfile.md 
      - Code of Conduct: docs/community/CODE_OF_CONDUCT.md
    - Developers:
      - Versions Matrix: docs/devs/versions.md
      - Releases: docs/devs/releases.md
theme:
  name: material
  features:
    - tabs

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: "#"
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.snippets
  - markdown_include.include:
      base_path: docs

plugins:
  - toc-sidebar
